/**
 * Danh sách Contract Size tĩnh cho 39 coin giao dịch trên MEXC Futures.
 * Đảm bảo hệ thống KHÔNG BAO GIỜ bị phụ thuộc vào file data/mexc-contracts.json (vốn bị .gitignore).
 * Ngăn chặn tuyệt đối lỗi tính sai khối lượng 10x-100x trên Railway!
 */
export const MEXC_CONTRACT_SPECS: Record<string, { contractSize: number; minVol: number; maxLeverage: number }> = {
  "BTC_USDT": { contractSize: 0.0001, minVol: 1, maxLeverage: 500 },
  "ETH_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 500 },
  "SOL_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 300 },
  "ZEC_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 150 },
  "XRP_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "NEAR_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "SUI_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "DOGE_USDT": { contractSize: 100, minVol: 1, maxLeverage: 300 },
  "TAO_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 300 },
  "HYPE_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 100 },
  "ADA_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "WLD_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "AVAX_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 200 },
  "ONDO_USDT": { contractSize: 10, minVol: 1, maxLeverage: 200 },
  "ENA_USDT": { contractSize: 10, minVol: 1, maxLeverage: 200 },
  "ARB_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "LINK_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 300 },
  "PEPE_USDT": { contractSize: 10000000, minVol: 1, maxLeverage: 300 },
  "1000PEPE_USDT": { contractSize: 1000, minVol: 1, maxLeverage: 300 },
  "INJ_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "LTC_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 200 },
  "FET_USDT": { contractSize: 10, minVol: 1, maxLeverage: 200 },
  "AAVE_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 200 },
  "DOT_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 300 },
  "HBAR_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "BNB_USDT": { contractSize: 0.01, minVol: 1, maxLeverage: 200 },
  "XLM_USDT": { contractSize: 10, minVol: 1, maxLeverage: 300 },
  "APT_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 200 },
  "RENDER_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "OP_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "TIA_USDT": { contractSize: 1, minVol: 1, maxLeverage: 300 },
  "JUP_USDT": { contractSize: 10, minVol: 1, maxLeverage: 200 },
  "LDO_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "SEI_USDT": { contractSize: 10, minVol: 1, maxLeverage: 300 },
  "ATOM_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 200 },
  "ALGO_USDT": { contractSize: 1, minVol: 1, maxLeverage: 200 },
  "WIF_USDT": { contractSize: 10, minVol: 1, maxLeverage: 50 },
  "ORDI_USDT": { contractSize: 0.1, minVol: 1, maxLeverage: 200 },
  "APE_USDT": { contractSize: 1, minVol: 1, maxLeverage: 50 },
};
